import Image from "next/image";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import Link from "next/link";

const FAQS = [
  {
    question: "What is a Certified Translation, and is it accepted by USCIS?",
    answer:
      "A certified translation includes a formal Certificate of Accuracy signed by a professional linguist, certifying fluency in both languages and exact word-for-word accuracy under 8 CFR 103.2(b)(3). VerifyLingua translations are 100% accepted by USCIS, the National Visa Center (NVC), federal courts, state licensing boards, and US universities.",
  },
  {
    question: "Do I need Notarization or an Apostille?",
    answer:
      "USCIS does not require notarization for standard green card or visa filings. However, state courts, foreign consulates, DMV driver licensing, and international adoptions often require notarization. If you're submitting documents abroad, an Apostille from the Secretary of State may also be needed. Our Acceptance Pre-Check Wizard automatically determines whether notarization is required for your receiving agency.",
  },
  {
    question: "How does the Pre-Payment AI Document Triage protect me?",
    answer:
      "Incumbents often take payment first, assign the document, and then cancel or issue a refund days later when an illegible handwriting note or missing page is discovered. Our vision model inspects resolution, glare, handwriting clarity, and missing pages within 5 seconds of upload, offering immediate re-shoot guidance before any payment is collected.",
  },
  {
    question: "What is the Name & Date Consistency Lock?",
    answer:
      "Name transliteration mismatches between civil documents (e.g. birth certificates) and foreign passports are the single most common cause of silent USCIS Requests for Evidence (RFEs). We ask for your exact passport spelling upfront and lock it into the translator workspace so government systems never encounter mismatched records.",
  },
  {
    question: "How does the Public QR Verification Portal work?",
    answer:
      "Every Certificate of Accuracy generated by VerifyLingua includes an encrypted QR code and short code resolving to /verify/{code}. Immigration adjudicators, university registrars, and consular officers can scan the code to instantly verify the cryptographic SHA-256 hash, translator credentials, and issuance status.",
  },
  {
    question: "What is the turnaround time and how is it calculated?",
    answer:
      "Standard orders of 1–3 pages are delivered in 24 hours or less. Expedited orders are delivered in 12 hours. Unlike competitors who provide vague '24-hour' estimates, our pricing engine calculates an exact deterministic delivery date and time (e.g., 'Tuesday, Sep 2, 9:00 AM EST') factoring in notarization batch timing.",
  },
  {
    question: "What is your USCIS 100% Acceptance Guarantee?",
    answer:
      "If your certified translation is rejected by USCIS for any translation accuracy or formatting defect, we will revise the document immediately for free and issue a 100% full refund of your order.",
  },
];

export function FAQSection() {
  return (
    <section className="py-20 md:py-28 bg-canvas border-b border-border/60">
      <div className="max-w-4xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-4">
          <span className="text-xs font-mono font-bold uppercase tracking-widest text-brand-500">
            Frequently Asked Questions
          </span>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-brand-ink tracking-tight font-display">
            Everything You Need to Know About Certified Translations
          </h2>
          <p className="text-base sm:text-lg text-ink-soft leading-relaxed">
            Have questions about government standards, notary requirements, or formatting? We have answers.
          </p>
        </div>

        <Accordion type="single" collapsible defaultValue="item-0" className="w-full">
          {FAQS.map((faq, idx) => (
            <AccordionItem key={idx} value={`item-${idx}`}>
              <AccordionTrigger className="text-left font-bold text-lg md:text-xl font-display">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-base text-ink-soft leading-relaxed pt-2 pb-6">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        <div className="p-8 sm:p-10 rounded-3xl bg-lavender-50/90 border border-border/80 flex flex-col sm:flex-row items-center justify-between gap-6 hover:shadow-md transition-shadow duration-300">
          <div className="flex items-center gap-5 text-left">
            <div className="relative w-20 h-20 rounded-2xl overflow-hidden border border-brand-100 bg-white shadow-sm shrink-0">
              <Image
                src="/images/step-human-cert-3d.jpg"
                alt="24/7 ATA accredited certified translation specialist"
                fill
                className="object-cover"
                sizes="80px"
              />
            </div>
            <div className="space-y-1">
              <h3 className="text-xl font-bold text-brand-ink font-display">Still have questions?</h3>
              <p className="text-sm text-ink-soft max-w-md">
                Our certified compliance specialists and ATA linguists are available 24/7 to review your document requirements before you order.
              </p>
            </div>
          </div>

          <div className="shrink-0">
            <Link
              href="/help"
              className="inline-flex items-center gap-2 h-12 px-6 rounded-xl bg-brand-500 hover:bg-brand-700 text-white text-sm font-bold shadow-sm transition-colors"
            >
              Ask Compliance Specialist →
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
