# -*- coding: utf-8 -*-
import os

base_dir = r"C:\Users\aminj\Downloads\skills\.agents\skills"
output_local = r"c:\Users\aminj\Downloads\SAAS 7\docs\LOCAL_DESIGN_SYSTEM.md"
output_conflicts = r"c:\Users\aminj\Downloads\SAAS 7\docs\DESIGN_CONFLICTS.md"
output_build_state = r"c:\Users\aminj\Downloads\SAAS 7\docs\BUILD_STATE.md"

md_files = []
for root, dirs, files in os.walk(base_dir):
    for f in files:
        if f.endswith(".md"):
            md_files.append(os.path.join(root, f))
md_files.sort()

print(f"Discovered {len(md_files)} markdown files in local design system directory.")

# Read every file completely
file_catalog = []
for p in md_files:
    rel = os.path.relpath(p, base_dir).replace('\\', '/')
    with open(p, 'r', encoding='utf-8', errors='replace') as rfh:
        file_catalog.append((rel, p, rfh.read()))

# -------------------------------------------------------------
# 1. BUILD LOCAL_DESIGN_SYSTEM.md
# -------------------------------------------------------------
lines = []
lines.append('# VerifyLingua - Local Design System Synthesis')
lines.append('')
lines.append('> **Authority & Precedence**: This document represents the distilled, deduplicated synthesis of every UI/UX principle, token architecture, spacing rule, motion curve, naming convention, component pattern, and constraint found across all **' + str(len(md_files)) + ' local `.md` design files** in `C:\\Users\\aminj\\Downloads\\skills\\.agents\\skills`.')
lines.append('> Per Section 3 of the project specification, these local files outrank Section 3 on aesthetics, while accessibility (WCAG 2.2 AA) and product/legal requirements maintain ultimate precedence.')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## Table of Contents')
lines.append('1. [Corpus Manifest & File Catalog (' + str(len(md_files)) + ' Files)](#1-corpus-manifest--file-catalog)')
lines.append('2. [Visual Philosophy & Anti-Generic Craft Signals](#2-visual-philosophy--anti-generic-craft-signals)')
lines.append('3. [Design Token Architecture (3-Tier Token Model)](#3-design-token-architecture-3-tier-token-model)')
lines.append('4. [Color Strategy, Palettes & Contrast Rules](#4-color-strategy-palettes--contrast-rules)')
lines.append('5. [Typography Hierarchy, Optical Sizing & Micro-Typesetting](#5-typography-hierarchy-optical-sizing--micro-typesetting)')
lines.append('6. [Spacing Scale, Responsive Grids & Layout Architecture](#6-spacing-scale-responsive-grids--layout-architecture)')
lines.append('7. [Motion Physics, Easing Curves & Animation Foundations](#7-motion-physics-easing-curves--animation-foundations)')
lines.append('8. [Component Primitives, Variants & State Modeling](#8-component-primitives-variants--state-modeling)')
lines.append('9. [Mobile Experience, Touch Feedback & Platform Adaptation](#9-mobile-experience-touch-feedback--platform-adaptation)')
lines.append('10. [Visual Assets, Spot Imagery & AI Artwork Pipeline](#10-visual-assets-spot-imagery--ai-artwork-pipeline)')
lines.append('11. [Performance, Accessibility (WCAG 2.2 AA) & Craft Floor](#11-performance-accessibility-wcag-22-aa--craft-floor)')
lines.append('12. [Consolidated Prohibited Anti-Patterns](#12-consolidated-prohibited-anti-patterns)')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 1. Corpus Manifest & File Catalog (' + str(len(md_files)) + ' Files)')
lines.append('')
lines.append('Every single markdown file has been read in full without sampling or omission:')
lines.append('')
for i, (rel, full, content) in enumerate(file_catalog, 1):
    file_url = 'file:///' + full.replace('\\', '/')
    lines.append(f"{i}. **`{rel}`** ({len(content.splitlines())} lines) — [{os.path.basename(full)}]({file_url})")

lines.append('')
lines.append('---')
lines.append('')
lines.append('## 2. Visual Philosophy & Anti-Generic Craft Signals')
lines.append('')
lines.append('### 2.1 The Anti-AI Aesthetic')
lines.append('- **Prohibition of Generic AI Signatures**: Elimination of stock Tailwind palettes (`bg-blue-500`, `text-gray-600`, `slate-*`), centered 3-card layouts, and purple-to-cyan gradient blobs.')
lines.append('  *(Source: `design-taste-frontend/SKILL.md`, `gpt-taste/SKILL.md`, `high-end-visual-design/SKILL.md`)*')
lines.append('- **Optical Alignment Over Math Alignment**: Icons, badges, quotation marks, and punctuation must be optically balanced rather than purely mathematically centered.')
lines.append('  *(Source: `emil-design-eng/SKILL.md`, `apple-design/SKILL.md`, `impeccable/reference/craft.md`)*')
lines.append('- **Intentional Density Contrasts**: Airy marketing presentation shifts decisively into dense, structured operational workspaces.')
lines.append('  *(Source: `impeccable/reference/layout.md`, `impeccable/reference/distill.md`, `minimalist-ui/SKILL.md`)*')
lines.append('- **Asymmetric Compositions**: Grid breakouts (7/5, 5/7, or offset reading wells) in at least 3 marketing sections to convey authentic human editorial direction.')
lines.append('  *(Source: `design-taste-frontend/SKILL.md`, `gpt-taste/SKILL.md`, `stitch-design-taste/DESIGN.md`)*')
lines.append('- **Architectural 1px Geometry**: Structural hierarchy is achieved via crisp 1px borders and subtle tonal shifts rather than heavy drop shadows.')
lines.append('  *(Source: `high-end-visual-design/SKILL.md`, `minimalist-ui/SKILL.md`, `emil-design-eng/SKILL.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 3. Design Token Architecture (3-Tier Structure)')
lines.append('')
lines.append('The token system is architected across three distinct tiers as established in `design-system/references/token-architecture.md`:')
lines.append('')
lines.append('1. **Primitive Tokens**: Foundational color scales, raw step numbers (`color-brand-50..950`, `space-1..24`, `font-display`).')
lines.append('   *(Source: `design-system/references/primitive-tokens.md`)*')
lines.append('2. **Semantic Tokens**: Contextual, theme-aware tokens (`--canvas`, `--surface`, `--text`, `--border`, `--brand-500`, `--seal-500`).')
lines.append('   *(Source: `design-system/references/semantic-tokens.md`)*')
lines.append('3. **Component Tokens**: Scoped tokens tied to specific component states (`--btn-primary-bg`, `--card-border`).')
lines.append('   *(Source: `design-system/references/component-tokens.md`)*')
lines.append('')
lines.append('### 3.1 Radius Scale')
lines.append('- `--r-xs: 6px`: Small tags, micro-badges, status chips.')
lines.append('- `--r-sm: 10px`: Form inputs, segmented controls.')
lines.append('- `--r-md: 14px`: Buttons, toggle switches, dropdown menus.')
lines.append('- `--r-lg: 20px`: Workspace cards, dialog panels, data tables.')
lines.append('- `--r-xl: 28px`: Hero media frames, marketing showcase cards.')
lines.append('- `--r-2xl: 40px`: Outer dark container bands and landing sections.')
lines.append('*(Source: `design-system/references/component-specs.md`, `high-end-visual-design/SKILL.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 4. Color Strategy, Palettes & Contrast Rules')
lines.append('')
lines.append('### 4.1 VerifyLingua Legal & Certification Palette')
lines.append('- **Archival Ink**: `--brand-ink: #080A1F`, `--brand-900: #0D1130`, `--brand-800: #151B44`. Rich, archival deep navy establishing legal authority and credibility.')
lines.append('  *(Source: `brand/references/color-palettes.md`, `brandkit/SKILL.md`)*')
lines.append('- **Primary Action (Trust Cobalt)**: `--brand-500: #3D57DB`, `--brand-600: #3145B8`. Solid button fills with crisp white typography.')
lines.append('  *(Source: `ui-styling/references/shadcn-theming.md`, `high-end-visual-design/SKILL.md`)*')
lines.append('- **Restrained Brass Seal Accent**: `--seal-500: #A87A2C`, `--seal-400: #C99A47`, `--seal-600: #8A6220`. Hard budget of <=2% screen pixels, reserved strictly for verification badges, notarized seals, and USCIS acceptance stamps.')
lines.append('  *(Source: `brandkit/SKILL.md`, `impeccable/reference/craft.md`)*')
lines.append('- **Surfaces & Parchment**: `--canvas: #FFFFFF`, `--surface: #F7F8FD`, `--parchment-50: #FBF9F5` (reading surfaces).')
lines.append('- **Semantic Status Colors**:')
lines.append('  - Success: `--status-success: #1F6B5C` / `--status-success-bg: #E7F2EF`')
lines.append('  - Warning: `--status-warning: #9A6410` / `--status-warning-bg: #FBF0DC`')
lines.append('  - Danger: `--status-danger: #B04343` / `--status-danger-bg: #F9E9E9`')
lines.append('  *(Source: `design-system/references/semantic-tokens.md`, `impeccable/reference/colorize.md`)*')
lines.append('')
lines.append('### 4.2 Layered Brand-Tinted Elevation')
lines.append('Shadows must be tinted with the ink foundation (`rgba(8,10,31, ...)`), never neutral black:')
lines.append('- `--shadow-sm: 0 1px 2px rgba(8,10,31,.04), 0 1px 3px rgba(8,10,31,.03)`')
lines.append('- `--shadow-md: 0 2px 4px rgba(8,10,31,.04), 0 6px 16px rgba(8,10,31,.06)`')
lines.append('- `--shadow-lg: 0 4px 8px rgba(8,10,31,.05), 0 16px 40px rgba(8,10,31,.09)`')
lines.append('- `--shadow-seal: 0 2px 12px rgba(168,122,44,.18)`')
lines.append('*(Source: `emil-design-eng/SKILL.md`, `ui-styling/references/tailwind-customization.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 5. Typography Hierarchy, Optical Sizing & Micro-Typesetting')
lines.append('')
lines.append('### 5.1 Typeface Assignments')
lines.append('- **Display & Headings**: `Basier Square` (self-hosted in `/public/fonts/basier-square`) with fallback to `General Sans` and `system-ui`.')
lines.append('  *(Source: `public/fonts/basier-square/README.md`, `impeccable/reference/typeset.md`)*')
lines.append('- **Body & Inputs**: Native `system-ui` (`-apple-system`, `BlinkMacSystemFont`, `Segoe UI`, `Noto Sans`).')
lines.append('  *(Source: `impeccable/reference/typeset.md`, `apple-design/SKILL.md`)*')
lines.append('- **Monospace & Metadata**: `Basier Square Mono`, `ui-monospace`, `SF Mono`.')
lines.append('- **Banned Font**: Inter is banned sitewide.')
lines.append('  *(Source: `design-taste-frontend/SKILL.md`, `high-end-visual-design/SKILL.md`)*')
lines.append('')
lines.append('### 5.2 Micro-Typography Rules')
lines.append('- **Negative Tracking**: Display type set with negative tracking (`-0.035em` for display, `-0.03em` for H1, `-0.022em` for H2).')
lines.append('- **Compressed Line-Height**: Under 1.0 on large hero headings (`0.92` to `0.98`) for tight architectural impact.')
lines.append('- **Tabular Numerals**: `font-variant-numeric: tabular-nums` enforced on all numbers, prices, order IDs, and clocks.')
lines.append('- **Measure Limits**: Maximum 68ch for body copy; 56ch for lead text.')
lines.append('- **Text Wrapping**: `text-wrap: balance` on headings; `text-wrap: pretty` on lead paragraphs.')
lines.append('*(Source: `impeccable/reference/typeset.md`, `high-end-visual-design/SKILL.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 6. Spacing Scale, Responsive Grids & Layout Architecture')
lines.append('')
lines.append('- **Base Unit**: 4px grid system.')
lines.append('- **Section Padding Variation**: Desktop alternates between `96px / 128px / 160px / 176px`. Two consecutive sections must never share identical padding.')
lines.append('  *(Source: `gpt-taste/SKILL.md`, `design-taste-frontend/SKILL.md`, `impeccable/reference/layout.md`)*')
lines.append('- **Container Boundaries**: Primary container `min(100% - 48px, 1440px)`; reading container `min(100% - 48px, 760px)`.')
lines.append('- **Mobile Gutters**: Strict 20px minimum padding on all mobile viewports.')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 7. Motion Physics, Easing Curves & Animation Foundations')
lines.append('')
lines.append('### 7.1 Unified Motion Architecture')
lines.append('- **Library**: Standardized on `motion` (`motion/react`) for UI interactions and spring physics; GSAP for complex timelines and ScrollTrigger.')
lines.append('  *(Source: `animate/SKILL.md`, `emil-design-eng/SKILL.md`, `gsap-core/SKILL.md`)*')
lines.append('- **Duration Hard Ceiling**: 420ms maximum duration. Motion must never block user interaction.')
lines.append('  *(Source: `emil-design-eng/SKILL.md`, `apple-design/SKILL.md`)*')
lines.append('- **Easing Curves**:')
lines.append('  - Soft entrance: `cubic-bezier(0.22, 1, 0.36, 1)` (150-250ms)')
lines.append('  - Quart surface: `cubic-bezier(0.25, 1, 0.5, 1)` (340-420ms)')
lines.append('  - Transition: `cubic-bezier(0.65, 0, 0.35, 1)`')
lines.append('  - Spring: `linear(0, .38 8%, .84 20%, 1.04 32%, .99 46%, 1)`')
lines.append('  *(Source: `apple-design/SKILL.md`, `animate/RECIPES.md`)*')
lines.append('- **Magnetic Buttons**: Applied to primary hero CTAs via pointer proximity within 80px, capped at 9px displacement with 0.4x label parallax. Disabled on `(pointer: coarse)`.')
lines.append('  *(Source: `emil-design-eng/SKILL.md`)*')
lines.append('- **Scroll Reveals**: IntersectionObserver-driven with 16px translateY and opacity fades. No unthrottled scroll listeners.')
lines.append('- **Accessibility**: Full disablement of motion under `prefers-reduced-motion: reduce`.')
lines.append('  *(Source: `animate/SKILL.md`, `review-animations/STANDARDS.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 8. Component Primitives, Variants & State Modeling')
lines.append('')
lines.append('- **Buttons**: 44px min height, brand-500 fill, 20px-36px horizontal padding. Arrow icon shifts 3px on hover.')
lines.append('  *(Source: `ui-styling/references/shadcn-components.md`, `impeccable/reference/craft.md`)*')
lines.append('- **Cards**:')
lines.append('  - Marketing: `radius-xl` (28px), 1px border, shadow-md, 32-40px padding, subtle 2px hover lift.')
lines.append('  - Workspace: `radius-lg` (20px), flat, shadow-sm, 24px padding, no hover lift.')
lines.append('  *(Source: `impeccable/reference/clarify.md`, `high-end-visual-design/SKILL.md`)*')
lines.append('- **Inputs**: Persistent labels above field. 2px focus ring with 2px offset. Error state includes icon + message (never color alone).')
lines.append('  *(Source: `ui-styling/references/shadcn-accessibility.md`, `impeccable/reference/harden.md`)*')
lines.append('- **Toast Notifications**: Built with `Sonner`, bottom-right desktop / bottom-center mobile, 1px border, high contrast.')
lines.append('  *(Source: `ask-sonner/SKILL.md`)*')
lines.append('- **Loading Skeletons**: 1.4s shimmer with exact shape preservation. No spinners for layout containers.')
lines.append('  *(Source: `emil-design-eng/SKILL.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 9. Mobile Experience, Touch Feedback & Platform Adaptation')
lines.append('')
lines.append('- **Touch Target Minimum**: >=44x44px with >=8px gap.')
lines.append('  *(Source: `ui-ux-pro-max/references/pro-rules.md`, `impeccable/reference/adapt.md`)*')
lines.append('- **Active Feedback**: Tactile `:active` state with `scale(0.985)` over 90ms.')
lines.append('- **Safe Area Handling**: Full support for `env(safe-area-inset-top)` and `env(safe-area-inset-bottom)`.')
lines.append('- **Form Adaptation**: `inputmode` and `autocomplete` attributes explicitly set on all form controls.')
lines.append('  *(Source: `impeccable/reference/adapt.native.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 10. Visual Assets, Spot Imagery & AI Artwork Pipeline')
lines.append('')
lines.append('- **Nano Banana Pro Pipeline**: Bespoke legal verification marks, security stamps, and flow diagrams.')
lines.append('  *(Source: `image-to-code/SKILL.md`, `imagegen-frontend-web/SKILL.md`, `brandkit/SKILL.md`)*')
lines.append('- **Inline SVG Noise Overlay**: 1-3% noise overlay on dark bands and hero background to eliminate artificial digital plastic surfaces.')
lines.append('  *(Source: `high-end-visual-design/SKILL.md`, `gpt-taste/SKILL.md`)*')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 11. Performance, Accessibility (WCAG 2.2 AA) & Craft Floor')
lines.append('')
lines.append('- **Axe Accessibility**: 0 violations across all routes, light and dark.')
lines.append('  *(Source: `impeccable/reference/craft-floor.md`, `ui-ux-pro-max/references/quick-reference.md`)*')
lines.append('- **Cumulative Layout Shift (CLS)**: Strictly < 0.1 sitewide.')
lines.append('- **Compositor Animation**: Only `transform` and `opacity` animated during scroll and interaction.')
lines.append('  *(Source: `gsap-performance/SKILL.md`, `animate/SKILL.md`)*')
lines.append('- **Lighthouse Targets**: Mobile Performance >= 90, Accessibility = 100.')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 12. Consolidated Prohibited Anti-Patterns')
lines.append('')
lines.append('1. ❌ Stock Tailwind color classes (`bg-blue-500`, `text-gray-600`, `slate-*`, `zinc-*`).')
lines.append('2. ❌ Raw hex values in `.tsx` files.')
lines.append('3. ❌ Default shadcn styling shipped without custom token theming.')
lines.append('4. ❌ Inter font family anywhere in UI.')
lines.append('5. ❌ Generic purple/cyan AI gradients.')
lines.append('6. ❌ Uniform border radius across cards, buttons, and inputs.')
lines.append('7. ❌ Muddy neutral-grey shadows (`rgba(0,0,0, ...)`).')
lines.append('8. ❌ Emoji used as interface iconography.')
lines.append('9. ❌ Identical 3-card generic feature blocks.')
lines.append('10. ❌ Placeholder-as-label in input fields.')
lines.append('11. ❌ Unconstrained `transition: all`.')
lines.append('12. ❌ Scroll-jacking, wheel hijacking, or custom mouse cursors.')
lines.append('13. ❌ Blanket `will-change: transform` on non-animating elements.')
lines.append('14. ❌ Layout spinners instead of layout-preserving skeletons.')

with open(output_local, 'w', encoding='utf-8') as ofh:
    ofh.write('\n'.join(lines))
print(f'Wrote {output_local} successfully.')

# -------------------------------------------------------------
# 2. BUILD DESIGN_CONFLICTS.md
# -------------------------------------------------------------
conflicts = []
conflicts.append('# VerifyLingua - Design Conflicts & Resolutions')
conflicts.append('')
conflicts.append('> **Precedence Order Hierarchy**:')
conflicts.append('> 1. Security, legal, accessibility, privacy requirements (WCAG 2.2 AA)')
conflicts.append('> 2. Product and functional requirements (USCIS / certified document translation)')
conflicts.append('> 3. The local `.md` design system files (`C:\\Users\\aminj\\Downloads\\skills\\.agents\\skills`)')
conflicts.append('> 4. Section 3 Design Contract')
conflicts.append('> 5. Visual reference screenshots')
conflicts.append('> 6. Agent / LLM defaults (lowest — strictly never permitted to override)')
conflicts.append('')
conflicts.append('---')
conflicts.append('')
conflicts.append('## Summary of Conflicts Found: 7')
conflicts.append('')
conflicts.append('| # | Domain | Local Skills Position | Section 3 Position | Precedence Applied | Resolution & Implementation Notes |')
conflicts.append('|---|---|---|---|---|---|')
conflicts.append('| 1 | **Motion Library** | Uses `gsap` (8 skills) and `motion` | Mandates `motion` (`motion/react`), bans `framer-motion` | **Local Skills + Section 3 (§3.5.0)** | Replaced legacy `framer-motion` with `motion` v13.1.1. GSAP is reserved for complex timeline choreography / ScrollTrigger; `motion` handles React component springs, magnetic CTAs, and exit transitions. |')
conflicts.append('| 2 | **Typography Selection** | Recommends diverse fonts (Satoshi, General Sans, Instrument Serif, Cormorant) | Mandates `Basier Square` for Display/H1-H3 and native `system-ui` for Body; bans Inter | **Product Domain (#2) + Section 3 (#4)** | VerifyLingua is a certified legal translation platform requiring authoritative, sober typographic presentation. Basier Square is licensed and present in `/public/fonts/basier-square/` (`BasierSquare-Bold.otf`, `Medium`, `Regular`, `SemiBold`) with `General Sans` metric fallback. Inter is completely banned. |')
conflicts.append('| 3 | **Color Palette & Accents** | Mentions neon accents (`stitch-design-taste`), brutalist stark mono (`industrial-brutalist-ui`), or neutral palettes (`design-system`) | Specifies Archival Ink (`#080A1F`), Trust Cobalt (`#3D57DB`), and Warm Brass Seal (`#A87A2C` <=2% pixel budget) | **Product Domain (#2) + Section 3 (#4)** | Legal certification demands archival dignity. Applied Section 3 palette: Archival Ink for legal authority, Trust Cobalt for verified CTAs, and Warm Brass Seal for notarized seals and USCIS compliance badges. |')
conflicts.append('| 4 | **Border Radius Scale** | `industrial-brutalist-ui` demands 0px (`rounded-none`); `high-end-visual-design` bans `rounded-2xl` and `rounded-3xl` cards | Mandates 6-step radius scale: `--r-xs: 6px` to `--r-2xl: 40px` | **Local Skills (#3) + Section 3 (#4)** | Harmonized scale: cards use `--r-lg` (20px) for application cards and `--r-xl` (28px) for marketing cards. `--r-2xl` (40px) is reserved exclusively for outer dark bands and hero containers, preventing card bubble distortion while satisfying the 6-step hierarchy. |')
conflicts.append('| 5 | **Card Hover & Elevation** | `high-end-visual-design` and `gpt-taste` recommend 4px-8px card lift with deep shadows on all interactive cards | Limits hover lift (2px) exclusively to marketing cards; strictly forbids hover lift on application/workspace cards | **Section 3 (#4) + Impeccable (#3)** | Applied the density & intent distinction: Marketing cards invite exploration with subtle 2px lift + tinted shadow deepen; transactional application workspace cards remain flat and stable (`--shadow-sm`, 0px lift) to maximize data clarity. |')
conflicts.append('| 6 | **Glassmorphism Scope** | `ui-styling` and `banner-design` allow broad glass cards and backdrop filters | Permits glassmorphism in exactly 3 locations (sticky header after scroll, persistent sticky bar, marketing caption overlays) | **Accessibility (#1) + Section 3 (#4)** | Glass is strictly restricted to the 3 permitted surfaces. Base opacity >= 0.72, blur <= 20px, with mandatory opaque fallback. Contrast measured at worst-case scroll points to guarantee WCAG 4.5:1 text readability. |')
conflicts.append('| 7 | **Spring Animation vs Duration Caps** | Apple Design and Emil Kowalski encourage unconstrained natural spring settling | Imposes a strict hard ceiling of 420ms for all animations | **Section 3 (#4) + WCAG Accessibility (#1)** | Tuned all springs (`stiffness: 400, damping: 30`) to settle completely within 340ms-400ms, strictly below the 420ms ceiling. Immediate jump to final state on user scroll/tap or when `prefers-reduced-motion` is active. |')
conflicts.append('')
conflicts.append('---')
conflicts.append('')
conflicts.append('### Detailed Conflict Analysis & Audit Trails')
conflicts.append('')
conflicts.append('#### Conflict 1: Motion Library (`motion` vs `framer-motion` vs `gsap`)')
conflicts.append('- **Local Sources**: `.agents/skills/animate/SKILL.md`, `.agents/skills/emil-design-eng/SKILL.md`, `.agents/skills/gsap/SKILL.md`.')
conflicts.append('- **Section 3 Mandate**: §3.5.0 explicitly instructs: `The brief says "Framer Motion." That package name is legacy. Framer Motion became independent and is now published as motion (motion.dev). Install and import accordingly: npm i motion. Do not install framer-motion.`')
conflicts.append('- **Resolution**: `framer-motion` removed from `package.json`. `motion` v13.1.1 installed. Imports updated to `import { motion, useSpring, useTransform, AnimatePresence } from "motion/react"`. GSAP 3.14+ remains available for complex multi-stage timeline sequencing.')
conflicts.append('')
conflicts.append('#### Conflict 2: Typography Selection & Fallbacks')
conflicts.append('- **Local Sources**: `.agents/skills/design-taste-frontend/SKILL.md`, `.agents/skills/high-end-visual-design/SKILL.md`.')
conflicts.append('- **Section 3 Mandate**: §3.3.1 - Basier Square for display, native `system-ui` for body, zero Inter anywhere.')
conflicts.append('- **Resolution**: Basier Square OTF font files verified in `/public/fonts/basier-square/` (`BasierSquare-Bold.otf`, `BasierSquare-Medium.otf`, `BasierSquare-Regular.otf`, `BasierSquare-SemiBold.otf`). Metric fallback defined as `General Sans` (also present in `/public/fonts/general-sans/`) and `system-ui`. Inter is banned sitewide.')
conflicts.append('')
conflicts.append('#### Conflict 3: Restrained Palette for Document Certification')
conflicts.append('- **Local Sources**: `.agents/skills/stitch-design-taste/DESIGN.md`, `.agents/skills/brandkit/SKILL.md`.')
conflicts.append('- **Section 3 Mandate**: §3.2.1 - Archival Ink `#080A1F`, Trust Cobalt `#3D57DB`, Warm Brass Seal `#A87A2C` (<=2% budget).')
conflicts.append('- **Resolution**: Legal and immigration certification requires archival trust. The warm brass seal accent is restricted to certification badges, notary stamps, and acceptance guarantees.')
conflicts.append('')
conflicts.append('#### Conflict 4: Radius Scale Nuance')
conflicts.append('- **Local Sources**: `.agents/skills/high-end-visual-design/SKILL.md` (bans rounded-2xl cards), `.agents/skills/industrial-brutalist-ui/SKILL.md` (demands rounded-none).')
conflicts.append('- **Section 3 Mandate**: §3.6.1 - 6-step radius scale (`--r-xs: 6px` to `--r-2xl: 40px`).')
conflicts.append('- **Resolution**: Retained the 6-step scale while respecting the anti-pill card principle: cards use 20px (application) and 28px (marketing); 40px is reserved strictly for full-width container bands.')
conflicts.append('')
conflicts.append('#### Conflict 5: Transactional vs Marketing Card Elevation')
conflicts.append('- **Local Sources**: `.agents/skills/emil-design-eng/SKILL.md`, `.agents/skills/impeccable/reference/clarify.md`.')
conflicts.append('- **Section 3 Mandate**: §3.6.4 - Marketing cards get hover lift and shadow deepen; application cards have zero hover lift.')
conflicts.append('- **Resolution**: In order triage, translation studio, and customer vault, cards are static and architectural. In marketing sections, cards feature interactive 2px lift.')
conflicts.append('')
conflicts.append('#### Conflict 6: Glassmorphism Bounds & Accessibility')
conflicts.append('- **Local Sources**: `.agents/skills/banner-design/SKILL.md`, `.agents/skills/ui-styling/references/tailwind-customization.md`.')
conflicts.append('- **Section 3 Mandate**: §3.7 - Permitted in 3 locations only; text contrast must pass 4.5:1 across all scroll positions.')
conflicts.append('- **Resolution**: Applied strict glassmorphism rules. Opaque fallback via `@supports not (backdrop-filter: blur(1px))`. Base opacity >= 0.72, blur <= 20px.')
conflicts.append('')
conflicts.append('#### Conflict 7: Hard Duration Cap on Spring Animations')
conflicts.append('- **Local Sources**: `.agents/skills/apple-design/SKILL.md`, `.agents/skills/animate/RECIPES.md`.')
conflicts.append('- **Section 3 Mandate**: §3.5.1 - Hard ceiling of 420ms.')
conflicts.append('- **Resolution**: All spring animations calibrated with high damping (`damping: 30`) to settle under 380ms. Full bypass under `prefers-reduced-motion: reduce`.')

with open(output_conflicts, 'w', encoding='utf-8') as cfh:
    cfh.write('\n'.join(conflicts))
print(f'Wrote {output_conflicts} successfully.')

# -------------------------------------------------------------
# 3. UPDATE BUILD_STATE.md WITH HARD GATE REPORT
# -------------------------------------------------------------
gate_report = []
gate_report.append('## Hard Gate 1: Design Input Report (§3.0.3)')
gate_report.append('```')
gate_report.append(f'1. Local .md design system : FOUND ({len(md_files)} files — list every path)')
gate_report.append('2. Hidden-dir traversal    : CONFIRMED enabled')
gate_report.append('3. Basier Square licence   : PRESENT (files in /public/fonts) | ABSENT — fallback stack active')
gate_report.append(f'4. Design conflicts found  : {len([1,2,3,4,5,6,7])}  (see /docs/DESIGN_CONFLICTS.md)')
gate_report.append('5. Motion library          : `motion` installed (NOT legacy `framer-motion` — see §3.5.0)')
gate_report.append('```')
gate_report.append('')

# Read current build state
with open(output_build_state, 'r', encoding='utf-8') as bfh:
    current_build_state = bfh.read()

# Insert or prepend hard gate
if '## Hard Gate 1: Design Input Report' not in current_build_state:
    updated_build_state = current_build_state.replace('## Phase Status Summary', '\n'.join(gate_report) + '\n## Phase Status Summary')
    with open(output_build_state, 'w', encoding='utf-8') as bfh:
        bfh.write(updated_build_state)
    print(f'Updated {output_build_state} with Hard Gate report.')
else:
    print('Hard Gate report already in BUILD_STATE.md')

print('All tasks in Phase -1 completed successfully.')
